site_name: Mycoriza
theme:
  name: material
  logo: assets/logo-white.png
  features:
    - header.autohide
    - navigation.sections
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      card: fontawesome/solid/sticky-note
repo_url: https://github.com/hsenid-mobile/mycoriza
edit_uri: ""
copyright: MIT
pages:
  - Overview: index.md
  - Guides:
    - Getting Started: getting-started.md
    - Migrate an existing project: migration-guide.md
    - API Response Handling: network-states.md
    - Patterns and Best Practices: patterns-and-best-practices.md
    - CLI Usage: cli-usage.md
    - Testing Components: how-to-test.md
  - Concepts:
    - Basic Concepts: concepts.md

markdown_extensions:
  - pymdownx.highlight
  - admonition
  - attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/prism.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/plugins/autoloader/prism-autoloader.min.js
#  - javascripts/config.js
extra_css:
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/themes/prism-okaidia.css
  - stylesheets/extra.css

extra:
  generator: false
