site_name: Mycoriza
theme:
  name: material
  features:
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/hsenid-mobile/mycoriza
edit_uri: ""
copyright: MIT
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Migrate an existing project: migration-guide.md
  - Concepts: concepts.md
  - API Response Handling: network-states.md
  - CLI Usage: cli-usage.md
  - Patterns and Best Practices: patterns-and-best-practices.md
  - Testing components: how-to-test.md

markdown_extensions:
  - pymdownx.highlight
  - admonition

extra_javascript:
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/prism.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/plugins/autoloader/prism-autoloader.min.js
#  - javascripts/config.js
extra_css:
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/themes/prism-okaidia.css

extra:
  generator: false
